"""Regenerate the initial content. Existing CMS records are never overwritten."""
import json
from pathlib import Path

services = []
def service(slug,title,description,icon,features,problem,approach):
    services.append(dict(slug=slug,title=title,description=description,icon=icon,features=features.split('|'),problem=problem,approach=approach,published=True))
service('custom-web-application-development','Custom web applications','Software shaped around the way your business actually works.','code','Workflow automation|Custom dashboards|User roles and permissions|Database design|Responsive interfaces','Spreadsheets, disconnected tools and repeated data entry can make simple operations difficult to manage.','We map the workflow first, define the people and decisions involved, and build a focused application around those requirements. You get a system designed for your operations, with a clear path for future improvements.')
service('laravel-development','Laravel development','A dependable backend for your next big idea.','terminal','Laravel and PHP|MySQL architecture|Authentication and authorization|Queues and Redis|Testing and deployment','A growing application needs more than a collection of features. It needs clear business rules, reliable data and code that can be maintained.','I build Laravel applications with explicit validation, scoped permissions and a structured data model. Background work goes into queues, and important workflows are tested before deployment.')
service('saas-development','SaaS & multi-tenant platforms','Turn your product idea into a platform built to grow.','layers','Multi-tenant architecture|Subscription billing|Tenant administration|Onboarding flows|Payment integration','A SaaS product must serve different organizations without mixing their data or making every customer a separate maintenance project.','We define the tenant boundary, access rules and subscription model early. I build the core product around a focused first release, with tenant-aware operations and a plan for onboarding, monitoring and growth.')
service('crm-development','CRM development','Keep your leads, customers and next steps connected.','grid','Lead management|Customer records|Sales pipeline|Follow-ups and tasks|Activity history|Notifications','When lead information lives in separate spreadsheets and conversations, follow-ups are easy to miss and sales activity is difficult to understand.','I bring customer records, ownership and next actions into one workflow. The pipeline reflects your sales process, so the team can see what needs attention without assembling information from multiple tools.')
service('hrms-development','HRMS & payroll systems','Make people operations clearer, from attendance to payroll.','grid','Employee management|Biometric attendance|Leave and comp off|Shifts and timesheets|Payroll and salary templates|Payslips|Policies and notifications','Attendance exceptions, changing shifts and different leave policies make payroll preparation time-consuming and difficult to verify.','We document policy rules and exception handling before development. Attendance, leave and payroll are connected through reviewable steps, with access controls for employee and salary information.')
service('erp-development','ERP development','Connect the operations that keep your business moving.','layers','Operational dashboards|Connected departments|Purchasing and orders|Approval workflows|Reporting|Roles and permissions','Separate departmental tools can create duplicate records and conflicting versions of the same business information.','I plan shared entities and ownership with your team, then connect modules incrementally. Explicit approval steps and traceable records help departments work from the same information.')
service('healthcare-management-system-development','Healthcare management systems','Connect patient enquiries with everyday healthcare operations.','shield','Patients and appointments|Enquiries|Billing and invoices|Expenses|Staff and services|Role-based permissions','A public website may collect enquiries while the operations team handles appointments, billing and staff in disconnected tools.','I connect enquiry capture with a purpose-built administration platform. Patient information and operational functions receive scoped permissions, and workflows are designed around the staff who use them.')
service('inventory-management-system-development','Inventory management systems','Know what is in stock, where it is and what happens next.','grid','Products and stock|Warehouses|Purchase and sales orders|Barcode management|Stock transfers|Stock movement history','Manual stock updates can leave teams with conflicting counts and little visibility into how inventory changed.','We define the stock movement model and validation rules first. Receiving, dispatch and transfers update inventory through recorded transactions so teams can trace adjustments and investigate differences.')
service('warehouse-management-system-development','Warehouse management systems','Bring structure to every movement through your warehouse.','layers','Inbound and putaway|Storage and retrieval|Inventory tracking|Cycle counting|Barcode integration|ERP and TMS integration','Warehouse teams need a consistent view of what arrived, where it was stored and what is ready to leave.','I build workflows around warehouse locations and inventory movements. Barcode-led steps, cycle counts and integration checkpoints help teams identify exceptions before they spread across connected systems.')
service('api-development-integration','API development & integration','Make your applications work better together.','link','REST APIs|Payment gateways|AWS S3 integration|Third-party services|Webhooks|Integration monitoring','Systems that cannot exchange information often leave your team copying records and resolving avoidable mismatches.','I design validated APIs and integration flows with clear authentication, failure handling and retry behavior. External responses are checked, and repeated events are handled carefully to avoid duplicate operations.')
service('laravel-maintenance','Maintenance & improvements','A practical way forward for the application you already have.','shield','Bug investigation and fixing|Feature improvements|Performance review|Dependency maintenance|Deployment support|Codebase review','An existing Laravel application can accumulate bugs, slow workflows or features that no longer fit the business.','I start by reproducing the issue and understanding the affected workflow. Changes stay focused, with regression checks and a deployment plan that accounts for the current application and its users.')
service('admin-panel-development','Admin panel development','Give your team the controls they need to run the business.','grid','Operational dashboards|User management|Role and permission management|Search and filters|Approval screens|Exports','Teams need safe, efficient ways to manage application data without relying on a developer for everyday changes.','I build admin interfaces around real tasks, with clear validation, permission checks and useful status information. Sensitive changes receive appropriate safeguards and deliberate review steps.')

projects=[]
def project(slug,title,short,theme,industry,categories,description,features,problem,solution,contribution,impact,related,architecture,tech='Laravel|PHP|MySQL',screenshots=None):
    projects.append(dict(slug=slug,title=title,short=short,theme=theme,icon='layers' if theme in ['warehouse','education'] else 'grid',industry=industry,categories=categories.split('|'),description=description,features=features.split('|'),problem=problem,solution=solution,contribution=contribution,impact=impact,related_services=related.split('|'),architecture=architecture,technologies=tech.split('|'),screenshots=screenshots or [],published=True))
project('bharat-medical-backoffice-management-system','Bharat Medical Hall','Bharat Medical','medical','Healthcare / Medical retail','Laravel|Healthcare', 'A centralized back-office system for orders, employees and everyday medical retail operations.','Order management|Employee management|Attendance management|User management|Role-based access control|Administrative management|Operational management','Medical retail operations involve more than fulfilling orders. Staff records, attendance and administrative responsibilities also need a consistent home. The project addressed the need to manage these internal processes from a centralized platform.','The back-office application brings order, employee and attendance management together, with role-based access to administrative functions. The structure gives the team one place to manage operational records.','I developed the custom back-office management system described here, including order, employee, attendance and user-management functionality.','The system provides a centralized workflow for internal operations. It supports clearer ownership of records and reduces the need to move between separate administrative processes. Quantified performance results have not been supplied.','healthcare-management-system-development|admin-panel-development','Role-based operations')
project('treeva-healthcare-management-system','Treeva Healthcare','Treeva Healthcare','treeva','Healthcare','Laravel|Healthcare|Website','A public-facing healthcare website connected to a complete patient and operations platform.','Patient management|Appointment management|Enquiry management|Billing and invoices|Expense management|Service management|Staff management|Users and permissions','The public-facing experience needed to explain healthcare services and collect patient enquiries and appointment requests. The internal team also needed a place to manage those requests alongside patient records, billing and daily operations.','The project combines a lead-focused public website with a healthcare administration platform. Enquiries and appointment requests become inputs to the operational workflow, while billing, services and staff are managed within the admin system.','My work covered the public website and the administration functionality outlined in this case study, connecting enquiry generation with healthcare operations.','The website and admin platform support a connected journey from initial enquiry to appointment and billing. The operational value is a shared workflow; no patient-growth or revenue figures are claimed.','healthcare-management-system-development|custom-web-application-development','Website + administration')
project('education-management-saas','Education Management SaaS','Campus / SaaS','education','Education','Laravel|SaaS','An institution management platform designed around scalable SaaS architecture.','Student management|Staff management|Attendance|Fee management|Academic management|User roles|Institution administration','Educational institutions need to coordinate student information, staff, attendance, academics and fees. A SaaS model adds the requirement to serve multiple institutions while maintaining appropriate organizational boundaries.','The platform groups institutional workflows within a SaaS application. Tenant-aware access and shared application architecture provide a foundation for adding institutions without duplicating the product for each organization.','My contribution focused on the education-management functionality and SaaS architecture described here, covering institutional records, permissions and administrative workflows.','The platform provides institutions with a consistent way to manage academic and administrative information. Its architecture supports growth across organizations; capacity and usage figures require production measurement.','saas-development|custom-web-application-development','Multi-tenant platform', 'Laravel|MySQL|SaaS')
project('crm-business-management-platform','CRM & Business Platform','Pipeline / CRM','crm','Sales / Business operations','Laravel|CRM|ERP','Connected leads, customer records and follow-ups for a more organized sales workflow.','Lead management|Customer management|Task management|Follow-ups|Activity tracking|Notifications|Sales process management','Sales teams need visibility into lead ownership, previous conversations and the next action. When those details are separated, following up consistently becomes difficult.','CRM functionality connects leads and customers with tasks, follow-ups and activity history. Sales process management gives the team a shared view of where an opportunity stands and what should happen next.','I developed CRM functionality covering the lead, customer, activity and task workflows described in this project.','Connected records make sales activity easier to review and help the team identify pending follow-ups. No conversion-rate or revenue improvements are asserted.','crm-development|erp-development','Connected sales workflows',screenshots=[{'src':'/assets/img/portfolio/crm/ERP1.png','alt':'Existing CRM dashboard asset showing navigation, analytics and activity overview'},{'src':'/assets/img/portfolio/crm/ERP2.png','alt':'Existing CRM application interface'}])
project('hrms-payroll-system','HRMS & Payroll System','People / HRMS','hrms','Human resources','Laravel|HRMS','Attendance, leave policies and payroll brought together in a structured employee management system.','Employee management|Attendance|Biometric integration|Leave management|Comp off|Shift management|Timesheets|Payroll|Salary templates|Payslip generation|Policies|Notifications','Payroll depends on more than a total of hours worked. Shift assignments, biometric events, leave balances, comp off and policy exceptions all affect the inputs that must be reviewed.','The HRMS connects employee records, attendance, leave and timesheets with payroll preparation. Salary templates and payslip generation support a repeatable payroll workflow, while policy handling accounts for the rules that shape attendance and leave decisions.','My development work covered the HRMS and payroll functionality listed here, including biometric attendance integration and the related employee-policy workflows.','The system brings payroll inputs into a connected process and helps make attendance and leave decisions more consistent. Payroll accuracy and time savings should be measured against real usage rather than assumed.','hrms-development|api-development-integration','Policy-driven workflows')
project('warehouse-management-system','Warehouse Management System','Warehouse / WMS','warehouse','Logistics / Warehousing','Laravel|Inventory|ERP|API','An operational platform connecting inbound, putaway, retrieval and inventory control.','Inbound management|Putaway|Storage and retrieval|Warehouse management|Inventory management|Cycle counting|Barcode integration|ERP integration|TMS integration','Warehouse operations depend on accurate location and movement information. Receiving, storing and retrieving stock must remain consistent with the inventory data used by connected ERP and transport systems.','The WMS organizes inventory through inbound, putaway, storage and retrieval workflows. Cycle counting and barcode integration support physical operations, with ERP and TMS integration connecting warehouse events to surrounding business systems.','I developed warehouse-management functionality across the workflows and integrations described in this case study.','The system supports traceable stock movements and a more consistent operational view of inventory. Inventory accuracy is a goal of the workflow; no unverified accuracy percentage is presented.','warehouse-management-system-development|inventory-management-system-development|api-development-integration','Warehouse + integrations')

technologies=[]
groups={
'Backend':{'Laravel':'My primary framework for business applications, authorization, validation and background jobs.','PHP':'The server-side foundation for application logic, integrations and maintainable business rules.','REST APIs':'Structured endpoints that connect interfaces, mobile clients and external services.'},
'Frontend':{'Vue.js':'Interactive application screens and reusable components for day-to-day workflows.','JavaScript':'Practical interface behavior, form interactions and API-driven experiences.','Tailwind CSS':'Consistent, responsive interfaces built from a deliberate design system.','Bootstrap':'Reliable interface components when maintaining or extending Bootstrap applications.','Livewire':'Reactive Laravel interfaces for forms, data tables and administrative workflows.','Inertia.js':'A bridge between Laravel routing and modern frontend application screens.','jQuery':'Targeted improvements and integration work in existing applications.','Vite':'Fast frontend builds and optimized asset delivery.'},
'Database':{'MySQL':'Relational data models, constraints and queries built around operational requirements.'},
'Infrastructure':{'Redis':'Caching and queue infrastructure where application workload calls for it.','Queues':'Background processing for notifications, imports and long-running tasks.','AWS S3':'Object storage for documents, uploads and other application files.','Linux Servers':'Application deployment, environment configuration and operational support.','Git':'Version control for traceable changes and collaborative development.'}}
for group,items in groups.items():
    for name,desc in items.items(): technologies.append(dict(slug=name.lower().replace(' ','-').replace('.',''),title=name,group=group,description=desc,published=True))

posts=[]
def post(slug,title,category,description,sections):
    posts.append(dict(slug=slug,title=title,category=category,description=description,date='2026-09-09',read_time=f'{max(3,round(sum(len(t.split()) for h,t in sections)/180))} min read',sections=[{'heading':h,'body':t} for h,t in sections],published=True))
post('custom-crm-development-cost','How much does it cost to build a custom CRM?','CRM','Understand the decisions that shape a custom CRM estimate, from workflows and integrations to migration and maintenance.',[
('Start with the workflow, not a price list','A useful CRM estimate begins with how your team finds, qualifies and serves customers. A system for a small team tracking leads and follow-ups is a different project from one connecting sales, support, invoicing and several external services. List the people who will use it, the decisions they make and the records they need. That gives a developer a concrete basis for scope.'),
('What changes the development effort','Custom pipeline stages, granular permissions, recurring tasks, reporting and approval rules all affect effort. Integrations add another dimension: an API may be straightforward, but handling failures, duplicate events and incomplete data still takes work. Data migration needs its own assessment, especially when existing spreadsheets contain inconsistent names or duplicate customers.'),
('Define a useful first release','Separate essential workflows from improvements that can follow. A focused first release might include lead capture, customer records, ownership, next actions and a simple pipeline. Advanced automation can follow once the team has used the core workflow. This approach makes scope easier to explain and reduces the risk of investing in features that do not fit everyday work.'),
('Ask for a transparent estimate','A project proposal should state the included workflows, assumptions, dependencies, acceptance criteria and how changes will be handled. Ask about deployment, migration, training and post-launch support as well as development. A responsible estimate is specific to the project; a universal fixed price would hide too many assumptions.'),
('Prepare for a project discussion','Bring sample spreadsheets with sensitive information removed, a description of your current sales process and the names of services the CRM must connect with. Explain what is most frustrating today and what a successful first release would change. These inputs are more useful than a long list of features without context.')])
post('custom-software-instead-of-excel','When your business outgrows spreadsheets','Business Software','Recognize when a shared spreadsheet should become a structured application, and how to approach the transition.',[
('Spreadsheets are a useful starting point','A spreadsheet is a flexible way to explore a process and organize small amounts of information. The question is whether the workflow still fits the tool. If people spend more time reconciling copies, repairing formulas or asking who changed a record than doing the underlying work, it may be time to review the system.'),
('Look for workflow problems','Repeated entry, unclear ownership, missing approvals and inconsistent access are signs of a process that needs more structure. A custom application can validate inputs, relate records and guide users through defined steps. Software will not resolve unclear business rules by itself, so document those rules before replacing the spreadsheet.'),
('Migrate one process at a time','Choose a workflow with a clear owner and measurable pain. Clean its source data, define the required fields and agree on the new source of truth. A staged migration lets the team verify the application against familiar records before more processes depend on it. Keep a controlled backup of the original data.'),
('Measure practical outcomes','Decide what you want to observe after launch: fewer duplicate records, faster retrieval, clearer approvals or less repeated entry. Establish a baseline before migration. This makes the business discussion about actual operational changes rather than a general promise that custom software will save time.')])
post('laravel-for-saas-applications','Choosing a foundation for your SaaS product','SaaS Development','A practical guide to evaluating Laravel for a SaaS application around your team, tenancy model and operating needs.',[
('Choose around the product','The right technical foundation depends on the product, the team maintaining it and the environment where it will run. For a business application with accounts, forms, permissions and background work, Laravel is one option to evaluate. Avoid choosing a framework only because it appears in a technology comparison.'),
('Make tenant boundaries explicit','A multi-tenant product needs a deliberate approach to organization identity and data access. Decide how requests identify a tenant, how records are scoped and what administrators can access. Tests should cover cross-tenant access attempts as well as normal workflows. A tenant identifier alone is not a complete isolation strategy.'),
('Design for operations early','Subscription events, email delivery, imports and external services create work beyond the request-response cycle. Plan retries, observability and handling for repeated events. Think about backups, deployment and support access before the first customer needs them. Operational clarity is part of product quality.'),
('Compare realistic alternatives','Evaluate alternatives against the same requirements: existing team knowledge, integration needs, hosting constraints and expected maintenance. Build a small representative workflow if a key requirement remains uncertain. This article is a planning guide, not a claim that one framework is faster or better for every SaaS product.')])
post('custom-hrms-employee-management','What a useful HRMS should do for your team','HRMS','Plan an HRMS around employee records, attendance exceptions, leave policies and reviewable payroll inputs.',[
('Connect the employee record','Employee information becomes more useful when attendance, leave and payroll reference the same person and employment context. Establish which records are authoritative and who can change them. Sensitive information requires careful access rules, and employees may need a different view from managers or payroll administrators.'),
('Write down policy exceptions','A policy that sounds simple can behave differently across shifts, holidays and partial-day leave. Gather examples from actual operations, including exceptions and corrections. Agree on effective dates for policy changes and how historical records should be treated. These decisions should guide development and acceptance checks.'),
('Make payroll inputs reviewable','Attendance events should not become unexplained salary numbers. The team needs to understand how attendance, leave and approved adjustments contribute to a payroll run. Provide a deliberate review step and a way to investigate discrepancies before finalization. The exact workflow should reflect the organization’s agreed policies.'),
('Roll out with the people who use it','Test representative records with HR and payroll staff before relying on the new system. Include overnight shifts, missing punches and changed leave decisions where relevant. A short, controlled parallel review can expose assumptions that ordinary happy-path examples miss.')])
post('warehouse-software-inventory-accuracy','Better inventory starts with traceable movements','Business Software','How warehouse workflows, barcodes and cycle counts support a more reliable view of stock.',[
('Record the movement, not just the balance','A stock balance says how much should be available; a movement history helps explain why. Receiving, putaway, transfers, retrieval and adjustments should follow defined rules. Record the item, quantity, source, destination and responsible operation as appropriate so discrepancies can be investigated.'),
('Match the physical workflow','Software steps should reflect how warehouse staff receive, locate and move goods. Barcode integration is useful when identifiers and scanning practices are consistent. Before implementation, check the location model, label conventions and common exceptions with the people doing the work.'),
('Use cycle counts to investigate differences','Cycle counting helps compare recorded inventory with physical stock in smaller, manageable groups. Define how discrepancies are reviewed and who can approve an adjustment. A count is most useful when the team can trace the transactions that explain a difference and improve the underlying process.'),
('Coordinate connected systems','ERP and transport integrations need clear ownership of records and events. Decide when a movement is confirmed, how failures are retried and how repeated messages are recognized. Inventory accuracy depends on disciplined workflows and reliable integration behavior; software alone does not guarantee a particular accuracy rate.')])
post('before-building-a-saas-product','Before you build a SaaS product, answer these questions','SaaS Development','Clarify your first customer, core workflow, tenant model and support needs before starting SaaS development.',[
('Who needs the first version?','Describe a specific customer and the problem they experience today. Understand what they currently use, how often the problem occurs and who decides to adopt a new tool. A focused customer profile makes feature decisions easier and keeps the first release connected to a real workflow.'),
('What is the smallest complete workflow?','A minimum release should still let a customer finish something useful. Define the beginning, the steps and the outcome of that workflow. Remove features that are interesting but not necessary to complete it. Establish acceptance criteria in language both the business and developer can assess.'),
('How will organizations and access work?','Decide whether customers are individuals or organizations, how people are invited and which roles they need. Clarify what happens when a user belongs to more than one organization. Tenant boundaries, onboarding and billing are connected product decisions that are expensive to leave ambiguous.'),
('Who will operate and support it?','Plan the responsibilities for deployment, backups, customer support and changes after launch. Determine what staff need to investigate an issue without unnecessary access to customer data. A SaaS product is an ongoing service, so the first-release plan should include its operation as well as its development.')])

faqs=[dict(slug='remote',title='Do you work with clients outside India?',answer='Yes. I work remotely with businesses in India and internationally. We agree on communication, review milestones and a practical meeting schedule before starting.',published=True),dict(slug='existing-projects',title='Can you improve an existing Laravel application?',answer='Yes. I can investigate bugs, add features, review performance and help with maintenance. I start by understanding the codebase and the affected business workflow.',published=True),dict(slug='estimate',title='How do you estimate a project?',answer='We discuss your requirements, priorities, integrations and timeline. I then define the scope and assumptions before preparing a quotation. The initial project discussion is free.',published=True),dict(slug='complete-system',title='Can you handle the complete application?',answer='My work spans backend development, interfaces, database design, APIs and deployment. We agree on the exact responsibilities and deliverables for your project before development begins.',published=True),dict(slug='support',title='What happens after launch?',answer='Deployment, handover and support expectations are agreed as part of the project. Ongoing maintenance and new features can be scoped separately as your requirements evolve.',published=True)]
data={'projects':projects,'services':services,'posts':posts,'technologies':technologies,'faqs':faqs,'testimonials':[], 'project_categories':[{'slug':s.lower(),'title':s,'published':True} for s in ['Laravel','SaaS','CRM','HRMS','Healthcare','ERP','Inventory','Website','API']], 'blog_categories':[{'slug':s.lower().replace(' ','-'),'title':s,'published':True} for s in ['Laravel','PHP','SaaS Development','Web Development','Business Software','CRM','HRMS','APIs','Software Development']]}
Path(__file__).resolve().parents[1].joinpath('app/content.json').write_text(json.dumps(data,ensure_ascii=False,indent=2),encoding='utf-8')
