<div class="container">
<header class="page-heading"><span class="eyebrow">LET’S BUILD SOMETHING USEFUL</span><h1>Tell me what you’d<br><span class="muted-heading">like to make easier.</span></h1><p>Too many spreadsheets, missed follow-ups or software that no longer fits? Describe the problem in your own words. You don’t need to know what to build yet.</p></header>
<div class="contact-layout"><aside class="contact-aside"><h2>A conversation.<br>Not a commitment.</h2><p>First, I’ll review what you share and contact you using your preferred method. We’ll discuss the problem, possible solutions and the next steps before a quotation. There’s no commitment to start a project.</p>
<a class="contact-link" href="mailto:<?=e($config['email'])?>"><?=icon('mail')?> <?=e($config['email'])?></a><a class="contact-link" href="tel:<?=e($config['phone_uri'])?>"><?=e($config['phone'])?></a>
<a class="button secondary contact-whatsapp" href="https://wa.me/916351716007" target="_blank" rel="noopener noreferrer">Prefer WhatsApp? Message me ↗</a>
<span class="remote"><?=icon('globe')?> India · Working remotely worldwide</span>
<div class="trust-list"><?php foreach(['A free initial discussion'=>'Explain the problem before deciding on a solution.','A plan you can understand'=>'We agree on the features, cost and responsibilities before starting.','Direct communication'=>'Speak with the developer who will build your software.'] as $h=>$p):?><div><?=icon('check')?><div><h3><?=$h?></h3><p><?=$p?></p></div></div><?php endforeach;?></div></aside>
<div><?php if($success):?><section class="success-panel" role="status"><?=icon('check')?><h2>Thank you. Your enquiry is in.</h2><p>Your project details have been saved. I’ll review them and follow up using your preferred contact method.</p><p>Enquiry reference: <strong>KP-<?=e($reference)?></strong></p><a class="text-link" href="/projects">Explore my work while you’re here <?=icon('arrow')?></a></section>
<?php else:?><?php if($errors):?><div class="error-summary" role="alert" tabindex="-1"><strong>Please check your enquiry.</strong><ul><?php foreach($errors as $error):?><li><?=e($error)?></li><?php endforeach;?></ul></div><?php endif;?>
<form id="inquiry-form" class="enquiry-form" action="/contact" method="post"><?=csrf()?><div class="honeypot" aria-hidden="true"><label for="website">Leave this field empty</label><input id="website" type="text" name="website" tabindex="-1" autocomplete="off"></div>
<div class="form-grid">
<div class="field"><label for="name">Your name *</label><input id="name" name="name" placeholder="Your full name" autocomplete="name" required minlength="2" maxlength="100" value="<?=e($old['name']??'')?>"></div>
<div class="field"><label for="company">Company <span>(optional)</span></label><input id="company" name="company" placeholder="Your company name" autocomplete="organization" maxlength="150" value="<?=e($old['company']??'')?>"></div>
<div class="field"><label for="email">Email address *</label><input id="email" name="email" type="email" placeholder="you@company.com" autocomplete="email" required maxlength="254" value="<?=e($old['email']??'')?>"></div>
<div class="field"><label for="phone">Phone number <span>(optional for email)</span></label><input id="phone" name="phone" type="tel" placeholder="Include country code" autocomplete="tel" maxlength="30" value="<?=e($old['phone']??'')?>"></div>
<div class="field"><label for="project_type">What would you like help with? *</label><select id="project_type" name="project_type" required><option value="">Choose a task, or select “Not sure yet”</option><?php foreach($types as $type):?><option value="<?=e($type)?>" <?=($old['project_type']??'')===$type?'selected':''?>><?=e($typeLabels[$type]??$type)?></option><?php endforeach;?></select></div>
<div class="field"><label for="budget">Budget range *</label><select id="budget" name="budget" required><?php foreach($budgets as $budget):?><option <?=($old['budget']??'Let’s discuss')===$budget?'selected':''?>><?=e($budget)?></option><?php endforeach;?></select></div>
<div class="field full"><label for="description">What is difficult to manage today? *</label><textarea id="description" name="description" required minlength="20" maxlength="10000" rows="6" placeholder="For example: I run a wholesale business. We track stock in Excel and often need to check several files before confirming an order. I want one place to see stock and sales."><?=e($old['description']??'')?></textarea></div>
<div class="field full"><label for="contact_method">How should I contact you? *</label><select id="contact_method" name="contact_method" required><?php foreach($methods as $method):?><option <?=($old['contact_method']??'Email')===$method?'selected':''?>><?=e($method)?></option><?php endforeach;?></select></div>
</div><p class="form-note">Please don’t include passwords, financial account details or patient information. Fields marked * are required.</p><label class="checkbox-label"><input type="checkbox" name="consent" value="yes" required <?=($_POST['consent']??'')==='yes'?'checked':''?>><span>I agree to my details being used to respond to this enquiry, as described in the <a class="text-link" href="/privacy">privacy notice</a>.</span></label>
<button type="submit" class="button">Request a free consultation <?=icon('diagonal')?></button><p class="form-note">No obligation. Just a useful first conversation.</p></form><?php endif;?></div></div></div>
